Dami/update to v anchor
webb-tools/protocol-ink pull request #28
Opened 2022-05-09 20:44 UTC by dharjeezy

closes #27

2022-05-16 11:05 UTC, drewstone requested changes

2022-05-16 11:32 UTC, dharjeezy commented on contracts/poseidon/Cargo.toml
> +arkworks-setups = { path = "/Users/Damilare/Documents/Webb/arkworks-gadgets/arkworks-setups",  features = ["r1cs"], default-features = false }
Yes, there is.
Here it is 
https://github.com/webb-tools/arkworks-gadgets/pull/213

2022-05-16 11:33 UTC, dharjeezy commented on contracts/vanchor/linkable_merkle_tree.rs
> +pub struct Edge {
There is actually no issue. I will update it

2022-05-16 11:33 UTC, dharjeezy commented on contracts/vanchor/zeroes.rs
> +pub fn zeroes(index: u32) -> [u8; 32] {
Alright

2022-05-20 15:40 UTC, drewstone commented on contracts/vanchor/linkable_merkle_tree.rs
> +    pub chain_id_list: ink_prelude::vec::Vec<ChainId>,
@dharjeezy the comment shouldn't be `// ///` it should just be `///`

2022-05-20 15:45 UTC, drewstone requested changes
Lots of things still need fixing here. Also I would consider using `derive(Encode, Decode)` for all the structs you're manually implementing it for. If `Decode` can't be derived then please work on implementing it properly.

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/vanchor_verifier/lib.rs
> +                (2, 2, 2) => include_bytes!("/Users/Damilare/Documents/Webb/protocol-substrate/protocol-substrate-fixtures/vanchor/bn254/x5/2-2-2/verifying_key.bin"),
These paths need to be fixed. I would consider hardcoding the verifying keys here instead of using paths since this is specific to your machine.

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/vanchor_verifier/Cargo.toml
> +	# Used for normal contract Wasm blobs.
Spacing is off

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/vanchor_verifier/Cargo.toml
> +	"cdylib",
Spacing is off

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/vanchor_verifier/Cargo.toml
> +arkworks-native-gadgets = { version = "0.5.3", default-features = false }
Version is old, should use 1.X.X

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/merkle_tree.rs
> +impl Decode for MerkleTree {
This doesn't seem like a right implementation of Decode, why not derive it? What is the error?

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/linkable_merkle_tree.rs
> +impl Decode for Edge {
Why not derive encode/decode traits instead? This shouldn't be left like this imo

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/Cargo.toml
> +	# Used for normal contract Wasm blobs.
spacing is off

2022-05-20 15:45 UTC, drewstone commented on contracts/vanchor/Cargo.toml
> +	"cdylib",
spacing is off

2022-05-20 15:45 UTC, drewstone commented on contracts/poseidon/Cargo.toml
> +arkworks-setups = { path = "/Users/Damilare/Documents/Webb/arkworks-gadgets/arkworks-setups",  features = ["r1cs"], default-features = false }
Use version not relative path.

2022-05-20 15:45 UTC, drewstone commented on contracts/poseidon/Cargo.toml
>  arkworks-native-gadgets = { version = "0.5.3", default-features = false }
Update version to 1.X.X

2022-05-20 15:46 UTC, drewstone commented on contracts/vanchor/linkable_merkle_tree.rs
> +impl Decode for LinkableMerkleTree {
Can we derive these traits?

2022-05-20 18:06 UTC, merged