Dami/add ci
webb-tools/protocol-ink pull request #42
Opened 2022-06-09 14:21 UTC by dharjeezy

closes #41

2022-06-20 14:32 UTC, drewstone requested changes
Can you fix up the commit history since lots of changes here seem to have been applied in previous PRs?

2022-06-20 14:32 UTC, drewstone commented on tests/util.ts
> +    const startArgs: string[] = [];
Tabs in typescript should be 2 spaced.

2022-06-20 14:32 UTC, drewstone commented on tests/util.ts
> +import {ChildProcess, spawn} from 'child_process';
Please add spaces to this imports
```suggestion
import { ChildProcess, spawn } from 'child_process';
```

2022-06-20 14:32 UTC, drewstone commented on tests/tokenWrapper.test.ts
> +import {ChildProcess, spawn} from 'child_process';
Please add spaces to imports 
```suggestion
import { ChildProcess, spawn } from 'child_process';
```

2022-06-20 14:32 UTC, drewstone commented on tests/tokenWrapper.test.ts
> +import {startContractNode} from "./util";
```suggestion
import { startContractNode } from "./util";
```

2022-06-21 08:48 UTC, closed without merging

2022-06-21 08:48 UTC, dharjeezy commented
closing this in honour of this #44 
the commit history is wrong